-- Local synthetic QA only. All fixtures roll back; no provider calls.
begin;
create extension if not exists pgtap with schema extensions;
select extensions.no_plan();
create function pg_temp.qid(text) returns uuid language sql immutable as $$ select md5('assistant0059:'||$1)::uuid $$;
create temp table qa_actions(name text primary key,id uuid);
grant all on qa_actions to authenticated;

insert into auth.users(id,email) values(pg_temp.qid('owner'),'qa-owner@example.test');
insert into auth.users(id,email) values(pg_temp.qid('admin'),'qa-admin@example.test');
insert into auth.users(id,email) values(pg_temp.qid('assistant'),'qa-assistant@example.test');
insert into auth.users(id,email) values(pg_temp.qid('doctorA'),'qa-doctora@example.test');
insert into auth.users(id,email) values(pg_temp.qid('doctorB'),'qa-doctorb@example.test');
insert into auth.users(id,email) values(pg_temp.qid('foreign'),'qa-foreign@example.test');
insert into auth.users(id,email) values(pg_temp.qid('basic'),'qa-basic@example.test');
insert into public.clinics(id,name,timezone) values(pg_temp.qid('north'),'Synthetic north','America/Mexico_City');
insert into public.clinic_subscriptions(clinic_id,plan_id,status,billing_provider) values(pg_temp.qid('north'),'plus','active','manual');
insert into public.clinics(id,name,timezone) values(pg_temp.qid('south'),'Synthetic south','America/Mexico_City');
insert into public.clinic_subscriptions(clinic_id,plan_id,status,billing_provider) values(pg_temp.qid('south'),'pro','active','manual');
insert into public.clinics(id,name,timezone) values(pg_temp.qid('basicClinic'),'Synthetic basicClinic','America/Mexico_City');
insert into public.clinic_subscriptions(clinic_id,plan_id,status,billing_provider) values(pg_temp.qid('basicClinic'),'basic','active','manual');
insert into public.clinic_members(id,clinic_id,user_id,role,status,is_professional) values(pg_temp.qid('memberowner'),pg_temp.qid('north'),pg_temp.qid('owner'),'owner','active',false);
insert into public.clinic_members(id,clinic_id,user_id,role,status,is_professional) values(pg_temp.qid('memberadmin'),pg_temp.qid('north'),pg_temp.qid('admin'),'admin','active',false);
insert into public.clinic_members(id,clinic_id,user_id,role,status,is_professional) values(pg_temp.qid('memberassistant'),pg_temp.qid('north'),pg_temp.qid('assistant'),'assistant','active',false);
insert into public.clinic_members(id,clinic_id,user_id,role,status,is_professional) values(pg_temp.qid('memberdoctorA'),pg_temp.qid('north'),pg_temp.qid('doctorA'),'doctor','active',true);
insert into public.clinic_members(id,clinic_id,user_id,role,status,is_professional) values(pg_temp.qid('memberdoctorB'),pg_temp.qid('north'),pg_temp.qid('doctorB'),'doctor','active',true);
insert into public.clinic_members(id,clinic_id,user_id,role,status,is_professional) values(pg_temp.qid('memberforeign'),pg_temp.qid('south'),pg_temp.qid('foreign'),'owner','active',true);
insert into public.clinic_members(id,clinic_id,user_id,role,status,is_professional) values(pg_temp.qid('memberbasic'),pg_temp.qid('basicClinic'),pg_temp.qid('basic'),'owner','active',true);
insert into public.patients(id,clinic_id,full_name,email) values(pg_temp.qid('patient1'),pg_temp.qid('north'),'Synthetic patient 1','patient1@example.test');
insert into public.patient_professional_assignments(clinic_id,patient_id,clinic_member_id,source) values(pg_temp.qid('north'),pg_temp.qid('patient1'),pg_temp.qid('memberdoctorA'),'manual');
insert into public.professional_availability_rules(clinic_id,clinic_member_id,weekday,start_time,end_time,effective_from) select pg_temp.qid('north'),pg_temp.qid('memberdoctorA'),d,'09:00','17:00','2026-01-01' from generate_series(1,5) d;
insert into public.patients(id,clinic_id,full_name,email) values(pg_temp.qid('patient2'),pg_temp.qid('north'),'Synthetic patient 2','patient2@example.test');
insert into public.patient_professional_assignments(clinic_id,patient_id,clinic_member_id,source) values(pg_temp.qid('north'),pg_temp.qid('patient2'),pg_temp.qid('memberdoctorB'),'manual');
insert into public.professional_availability_rules(clinic_id,clinic_member_id,weekday,start_time,end_time,effective_from) select pg_temp.qid('north'),pg_temp.qid('memberdoctorB'),d,'09:00','17:00','2026-01-01' from generate_series(1,5) d;
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('basic')::text,true);
select extensions.throws_ok($t$select * from public.list_appointment_assistant_activity_for_current_user(pg_temp.qid('basicClinic'))$t$,'42501',null,'Basic empty-clinic activity explicitly denied');
select extensions.throws_ok($t$select * from public.get_appointment_automation_dashboard_for_current_user(pg_temp.qid('basicClinic'))$t$,'42501',null,'Basic empty-clinic dashboard explicitly denied');
select extensions.throws_ok($t$select * from public.get_appointment_automation_scheduler_status_for_current_user(pg_temp.qid('basicClinic'))$t$,'42501',null,'Basic scheduler denied');
select extensions.throws_ok($t$select public.save_appointment_assistant_settings_for_current_user(pg_temp.qid('basicClinic'),true,true,24,null,null,true)$t$,'42501',null,'Basic settings denied');
select extensions.throws_ok($t$select * from public.create_assistant_pending_action_for_current_user(pg_temp.qid('basicClinic'),'cancel_appointment','{}',now()+interval '5 minutes')$t$,'42501',null,'Basic direct proposal denied');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
insert into qa_actions select 'drift',id from (select * from public.create_assistant_pending_action_for_current_user(pg_temp.qid('north'),'create_appointment',jsonb_build_object('patient_id',pg_temp.qid('patient1'),'professional_clinic_member_id',pg_temp.qid('memberdoctorA'),'local_date','2030-01-07','local_time','10:00','duration_minutes',30),now()+interval '5 minutes')) q;
reset role; update public.clinic_subscriptions set plan_id='basic' where clinic_id=pg_temp.qid('north');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.throws_ok($t$select * from public.claim_assistant_pending_action_for_current_user((select id from qa_actions where name='drift'))$t$,'42501',null,'Plus to Basic claim denied');
select extensions.is((select status from public.assistant_pending_actions where id=(select id from qa_actions where name='drift')),'pending'::text,'Denied claim retains pending proposal');
select extensions.lives_ok($t$select public.cancel_assistant_pending_action_for_current_user((select id from qa_actions where name='drift'))$t$,'Basic may safely cancel pending proposal');
reset role; update public.clinic_subscriptions set plan_id='plus' where clinic_id=pg_temp.qid('north');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.lives_ok($t$select * from public.create_assistant_pending_action_for_current_user(pg_temp.qid('north'),'create_appointment',jsonb_build_object('patient_id',pg_temp.qid('patient1'),'professional_clinic_member_id',pg_temp.qid('memberdoctorA'),'local_date','2030-01-07','local_time','10:00','duration_minutes',30),now()+interval '5 minutes')$t$,'plus writable proposal allowed');
reset role; update public.clinic_subscriptions set plan_id='pro' where clinic_id=pg_temp.qid('north');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.lives_ok($t$select * from public.create_assistant_pending_action_for_current_user(pg_temp.qid('north'),'create_appointment',jsonb_build_object('patient_id',pg_temp.qid('patient1'),'professional_clinic_member_id',pg_temp.qid('memberdoctorA'),'local_date','2030-01-07','local_time','10:00','duration_minutes',30),now()+interval '5 minutes')$t$,'pro writable proposal allowed');
insert into qa_actions select 'execution',id from (select * from public.create_assistant_pending_action_for_current_user(pg_temp.qid('north'),'create_appointment',jsonb_build_object('patient_id',pg_temp.qid('patient1'),'professional_clinic_member_id',pg_temp.qid('memberdoctorA'),'local_date','2030-01-07','local_time','10:00','duration_minutes',30),now()+interval '5 minutes')) q;
select extensions.lives_ok($t$select * from public.claim_assistant_pending_action_for_current_user((select id from qa_actions where name='execution'))$t$,'Claim while entitled');
reset role; update public.clinic_subscriptions set plan_id='basic',status='active' where clinic_id=pg_temp.qid('north');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.throws_ok($t$select * from public.execute_claimed_assistant_pending_action_for_current_user((select id from qa_actions where name='execution'))$t$,'42501',null,'Claim then basic: execution denied');
reset role;
select extensions.is((select count(*)::integer from public.appointments where clinic_id=pg_temp.qid('north')),0,'Denied execution performs zero appointment mutation');
reset role; update public.clinic_subscriptions set plan_id='plus',status='past_due' where clinic_id=pg_temp.qid('north');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.throws_ok($t$select * from public.execute_claimed_assistant_pending_action_for_current_user((select id from qa_actions where name='execution'))$t$,'42501',null,'Claim then past_due: execution denied');
reset role;
select extensions.is((select count(*)::integer from public.appointments where clinic_id=pg_temp.qid('north')),0,'Denied execution performs zero appointment mutation');
reset role; update public.clinic_subscriptions set plan_id='plus',status='inactive' where clinic_id=pg_temp.qid('north');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.throws_ok($t$select * from public.execute_claimed_assistant_pending_action_for_current_user((select id from qa_actions where name='execution'))$t$,'42501',null,'Claim then inactive: execution denied');
reset role;
select extensions.is((select count(*)::integer from public.appointments where clinic_id=pg_temp.qid('north')),0,'Denied execution performs zero appointment mutation');
reset role; update public.clinic_subscriptions set plan_id='plus',status='cancelled' where clinic_id=pg_temp.qid('north');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.throws_ok($t$select * from public.execute_claimed_assistant_pending_action_for_current_user((select id from qa_actions where name='execution'))$t$,'42501',null,'Claim then cancelled: execution denied');
reset role;
select extensions.is((select count(*)::integer from public.appointments where clinic_id=pg_temp.qid('north')),0,'Denied execution performs zero appointment mutation');
update public.clinic_subscriptions set plan_id='plus',status='active' where clinic_id=pg_temp.qid('north');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.lives_ok($t$select * from public.execute_claimed_assistant_pending_action_for_current_user((select id from qa_actions where name='execution'))$t$,'Assistant SQL creates through canonical RPC');
select extensions.throws_ok($t$select * from public.execute_claimed_assistant_pending_action_for_current_user((select id from qa_actions where name='execution'))$t$,'42501',null,'Second execution before finish denied');
reset role;
select extensions.is((select count(*)::integer from public.appointments where clinic_id=pg_temp.qid('north')),1,'Exactly one appointment created');
select extensions.is((select starts_at from public.appointments where clinic_id=pg_temp.qid('north')),'2030-01-07 16:00:00+00'::timestamptz,'Clinic Mexico local time converts to UTC correctly');
select extensions.is((select count(*)::integer from public.appointment_events where clinic_id=pg_temp.qid('north') and event_type='created'),1,'Canonical created event preserved');
update public.clinic_subscriptions set plan_id='basic' where clinic_id=pg_temp.qid('north');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.lives_ok($t$select public.finish_assistant_pending_action_for_current_user((select id from qa_actions where name='execution'),'executed',null)$t$,'Finish after downgrade permitted');
reset role; update public.clinic_subscriptions set plan_id='plus' where clinic_id=pg_temp.qid('north');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
insert into qa_actions select 'confirm_appointment',id from public.create_assistant_pending_action_for_current_user(pg_temp.qid('north'),'confirm_appointment',jsonb_build_object('appointment_id',(select id from public.appointments where clinic_id=pg_temp.qid('north')),'expected_status','scheduled'),now()+interval '5 minutes');
select extensions.lives_ok($t$select * from public.claim_assistant_pending_action_for_current_user((select id from qa_actions where name='confirm_appointment'))$t$,'confirm_appointment claim');
select extensions.lives_ok($t$select * from public.execute_claimed_assistant_pending_action_for_current_user((select id from qa_actions where name='confirm_appointment'))$t$,'confirm_appointment canonical execution');
select extensions.lives_ok($t$select public.finish_assistant_pending_action_for_current_user((select id from qa_actions where name='confirm_appointment'),'executed',null)$t$,'confirm_appointment finish');
insert into qa_actions select 'reschedule_appointment',id from public.create_assistant_pending_action_for_current_user(pg_temp.qid('north'),'reschedule_appointment',jsonb_build_object('appointment_id',(select id from public.appointments where clinic_id=pg_temp.qid('north')),'expected_status','confirmed','local_date','2030-01-07','local_time','11:00','duration_minutes',30),now()+interval '5 minutes');
select extensions.lives_ok($t$select * from public.claim_assistant_pending_action_for_current_user((select id from qa_actions where name='reschedule_appointment'))$t$,'reschedule_appointment claim');
select extensions.lives_ok($t$select * from public.execute_claimed_assistant_pending_action_for_current_user((select id from qa_actions where name='reschedule_appointment'))$t$,'reschedule_appointment canonical execution');
select extensions.lives_ok($t$select public.finish_assistant_pending_action_for_current_user((select id from qa_actions where name='reschedule_appointment'),'executed',null)$t$,'reschedule_appointment finish');
insert into qa_actions select 'cancel_appointment',id from public.create_assistant_pending_action_for_current_user(pg_temp.qid('north'),'cancel_appointment',jsonb_build_object('appointment_id',(select id from public.appointments where clinic_id=pg_temp.qid('north')),'expected_status','confirmed'),now()+interval '5 minutes');
select extensions.lives_ok($t$select * from public.claim_assistant_pending_action_for_current_user((select id from qa_actions where name='cancel_appointment'))$t$,'cancel_appointment claim');
select extensions.lives_ok($t$select * from public.execute_claimed_assistant_pending_action_for_current_user((select id from qa_actions where name='cancel_appointment'))$t$,'cancel_appointment canonical execution');
select extensions.lives_ok($t$select public.finish_assistant_pending_action_for_current_user((select id from qa_actions where name='cancel_appointment'),'executed',null)$t$,'cancel_appointment finish');
reset role; insert into public.appointments(id,clinic_id,patient_id,doctor_id,title,starts_at,ends_at) values(pg_temp.qid('appointmentB'),pg_temp.qid('north'),pg_temp.qid('patient2'),pg_temp.qid('doctorB'),'Synthetic B','2030-01-07 15:00+00','2030-01-07 15:30+00');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
insert into qa_actions select 'cancelDenied',id from public.create_assistant_pending_action_for_current_user(pg_temp.qid('north'),'cancel_appointment',jsonb_build_object('appointment_id',pg_temp.qid('appointmentB'),'expected_status','scheduled'),now()+interval '5 minutes');
select extensions.lives_ok($t$select * from public.claim_assistant_pending_action_for_current_user((select id from qa_actions where name='cancelDenied'))$t$,'Cancel claim while Plus');
reset role; update public.clinic_subscriptions set plan_id='basic' where clinic_id=pg_temp.qid('north');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.throws_ok($t$select * from public.execute_claimed_assistant_pending_action_for_current_user((select id from qa_actions where name='cancelDenied'))$t$,'42501',null,'Assistant cancel denied after downgrade');
select extensions.lives_ok($t$select * from public.mutate_appointment_lifecycle_for_current_user(pg_temp.qid('north'),pg_temp.qid('appointmentB'),'cancel','scheduled',null,null)$t$,'Normal Basic Agenda safe cancellation unchanged');
reset role; update public.clinic_subscriptions set plan_id='plus' where clinic_id=pg_temp.qid('north');
insert into public.audit_logs(clinic_id,actor_user_id,entity_type,entity_id,action,metadata) select clinic_id,pg_temp.qid('owner'),'appointment',id,'appointment_cancelled','{"private":"not returned"}' from public.appointments where clinic_id=pg_temp.qid('north');
insert into public.appointment_invites(clinic_id,appointment_id,patient_id,channel,ics_uid,sequence,delivery_status,last_idempotency_key,last_method) select clinic_id,id,patient_id,'email',id::text,0,'sent','qa-key-'||id::text,'CANCEL' from public.appointments where clinic_id=pg_temp.qid('north');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.is((select count(*)::integer from (select * from public.list_appointment_assistant_activity_for_current_user(pg_temp.qid('north'),null,null,null,50)) a),10,'owner sees all three activity sources in clinic');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('admin')::text,true);
select extensions.is((select count(*)::integer from (select * from public.list_appointment_assistant_activity_for_current_user(pg_temp.qid('north'),null,null,null,50)) a),10,'admin sees all three activity sources in clinic');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('assistant')::text,true);
select extensions.is((select count(*)::integer from (select * from public.list_appointment_assistant_activity_for_current_user(pg_temp.qid('north'),null,null,null,50)) a),10,'assistant sees all three activity sources in clinic');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('doctorA')::text,true);
select extensions.is((select count(*)::integer from (select * from public.list_appointment_assistant_activity_for_current_user(pg_temp.qid('north'),null,null,null,50)) a where appointment_id=pg_temp.qid('appointmentB')),0,'Doctor A never sees doctor B activity');
select extensions.is((select count(distinct event_source)::integer from (select * from public.list_appointment_assistant_activity_for_current_user(pg_temp.qid('north'),null,null,null,50)) a),3,'Doctor A sees own three activity sources');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('foreign')::text,true);
select extensions.throws_ok($t$select * from public.list_appointment_assistant_activity_for_current_user(pg_temp.qid('north'),null,null,null,50)$t$,'42501',null,'Cross tenant activity denied');
reset role; update public.clinic_subscriptions set plan_id='basic',status='active',current_period_end=null where clinic_id=pg_temp.qid('north');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.throws_ok($t$select * from public.list_appointment_assistant_activity_for_current_user(pg_temp.qid('north'),null,null,null,50)$t$,'42501',null,'Basic activity denied');
select extensions.throws_ok($t$select * from public.create_assistant_pending_action_for_current_user(pg_temp.qid('north'),'create_appointment',jsonb_build_object('patient_id',pg_temp.qid('patient1'),'professional_clinic_member_id',pg_temp.qid('memberdoctorA'),'local_date','2030-01-07','local_time','10:00','duration_minutes',30),now()+interval '5 minutes')$t$,'42501',null,'basic/active new proposal denied');
reset role; update public.clinic_subscriptions set plan_id='plus',status='past_due',current_period_end=null where clinic_id=pg_temp.qid('north');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.lives_ok($t$select * from public.list_appointment_assistant_activity_for_current_user(pg_temp.qid('north'),null,null,null,50)$t$,'plus/past_due history retained');
select extensions.throws_ok($t$select * from public.create_assistant_pending_action_for_current_user(pg_temp.qid('north'),'create_appointment',jsonb_build_object('patient_id',pg_temp.qid('patient1'),'professional_clinic_member_id',pg_temp.qid('memberdoctorA'),'local_date','2030-01-07','local_time','10:00','duration_minutes',30),now()+interval '5 minutes')$t$,'42501',null,'plus/past_due new proposal denied');
reset role; update public.clinic_subscriptions set plan_id='pro',status='cancelled',current_period_end=null where clinic_id=pg_temp.qid('north');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.lives_ok($t$select * from public.list_appointment_assistant_activity_for_current_user(pg_temp.qid('north'),null,null,null,50)$t$,'pro/cancelled history retained');
select extensions.throws_ok($t$select * from public.create_assistant_pending_action_for_current_user(pg_temp.qid('north'),'create_appointment',jsonb_build_object('patient_id',pg_temp.qid('patient1'),'professional_clinic_member_id',pg_temp.qid('memberdoctorA'),'local_date','2030-01-07','local_time','10:00','duration_minutes',30),now()+interval '5 minutes')$t$,'42501',null,'pro/cancelled new proposal denied');
reset role; update public.clinic_subscriptions set plan_id='plus',status='trialing',current_period_end=now()-interval '1 day' where clinic_id=pg_temp.qid('north');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.lives_ok($t$select * from public.list_appointment_assistant_activity_for_current_user(pg_temp.qid('north'),null,null,null,50)$t$,'plus/trialing history retained');
select extensions.throws_ok($t$select * from public.create_assistant_pending_action_for_current_user(pg_temp.qid('north'),'create_appointment',jsonb_build_object('patient_id',pg_temp.qid('patient1'),'professional_clinic_member_id',pg_temp.qid('memberdoctorA'),'local_date','2030-01-07','local_time','10:00','duration_minutes',30),now()+interval '5 minutes')$t$,'42501',null,'plus/trialing new proposal denied');
reset role; update public.clinic_subscriptions set plan_id='pro',status='trialing',current_period_end=null where clinic_id=pg_temp.qid('north');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.lives_ok($t$select * from public.list_appointment_assistant_activity_for_current_user(pg_temp.qid('north'),null,null,null,50)$t$,'pro/trialing history retained');
select extensions.throws_ok($t$select * from public.create_assistant_pending_action_for_current_user(pg_temp.qid('north'),'create_appointment',jsonb_build_object('patient_id',pg_temp.qid('patient1'),'professional_clinic_member_id',pg_temp.qid('memberdoctorA'),'local_date','2030-01-07','local_time','10:00','duration_minutes',30),now()+interval '5 minutes')$t$,'42501',null,'pro/trialing new proposal denied');
reset role; update public.clinic_subscriptions set plan_id='plus',status='trialing',current_period_end=now()+interval '1 day' where clinic_id=pg_temp.qid('north');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.lives_ok($t$select * from public.list_appointment_assistant_activity_for_current_user(pg_temp.qid('north'),null,null,null,50)$t$,'plus/trialing history retained');
select extensions.lives_ok($t$select * from public.create_assistant_pending_action_for_current_user(pg_temp.qid('north'),'create_appointment',jsonb_build_object('patient_id',pg_temp.qid('patient1'),'professional_clinic_member_id',pg_temp.qid('memberdoctorA'),'local_date','2030-01-07','local_time','10:00','duration_minutes',30),now()+interval '5 minutes')$t$,'Valid trial proposal permitted');
-- Direct execution regression: reuse canonical scheduling checks, not TS mocks.
reset role;
update public.clinic_subscriptions set plan_id='plus',status='active',current_period_end=null where clinic_id=pg_temp.qid('north');
create function pg_temp.qa_execute(p_args jsonb,p_tool text default 'create_appointment') returns uuid language plpgsql as $$
declare v_id uuid; v_result uuid;
begin
 select id into v_id from public.create_assistant_pending_action_for_current_user(pg_temp.qid('north'),p_tool,p_args,now()+interval '5 minutes');
 perform public.claim_assistant_pending_action_for_current_user(v_id);
 select appointment_id into v_result from public.execute_claimed_assistant_pending_action_for_current_user(v_id);
 return v_result;
end; $$;
create function pg_temp.qa_create_args(p_patch jsonb default '{}') returns jsonb language sql as $$
 select jsonb_build_object('patient_id',pg_temp.qid('patient1'),'professional_clinic_member_id',pg_temp.qid('memberdoctorA'),'local_date','2030-01-08','local_time','10:00','duration_minutes',30)||p_patch;
$$;
set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
insert into qa_actions values ('newAppointment',pg_temp.qa_execute(pg_temp.qa_create_args()));
select extensions.throws_ok($t$select pg_temp.qa_execute(pg_temp.qa_create_args())$t$,'23P01',null,'Canonical conflict still denied');
select extensions.throws_ok($t$select pg_temp.qa_execute(pg_temp.qa_create_args('{"local_time":"18:00"}'))$t$,'23P01',null,'Canonical outside availability denied');
select extensions.throws_ok($t$select pg_temp.qa_execute(pg_temp.qa_create_args(jsonb_build_object('patient_id',pg_temp.qid('patient2'))))$t$,'42501',null,'Patient assigned to another professional denied');
select extensions.throws_ok($t$select pg_temp.qa_execute(pg_temp.qa_create_args(jsonb_build_object('professional_clinic_member_id',pg_temp.qid('memberforeign'))))$t$,'42501',null,'Cross tenant professional denied');
select extensions.throws_ok($t$select pg_temp.qa_execute(pg_temp.qa_create_args(jsonb_build_object('professional_clinic_member_id',pg_temp.qid('missing'))))$t$,'42501',null,'Nonexistent professional denied');
select extensions.throws_ok($t$select pg_temp.qa_execute(pg_temp.qa_create_args('{"local_date":null}'))$t$,'22023',null,'Missing scheduling data denied');
select extensions.throws_ok($t$select pg_temp.qa_execute(jsonb_build_object('appointment_id',(select id from qa_actions where name='newAppointment'),'expected_status','confirmed'),'reschedule_appointment')$t$,'22023',null,'Reschedule requires validated local scheduling data');
select extensions.throws_ok($t$select pg_temp.qa_execute(jsonb_build_object('appointment_id',(select id from qa_actions where name='newAppointment'),'expected_status','confirmed'),'cancel_appointment')$t$,'40001',null,'Expected status contract preserved');
select extensions.throws_ok($t$select pg_temp.qa_execute(jsonb_build_object('appointment_id',(select id from qa_actions where name='newAppointment')),'cancel_appointment')$t$,'22023',null,'Lifecycle expected status cannot be bypassed by direct pending payload');
select extensions.is((select doctor_id from public.appointments where id=(select id from qa_actions where name='newAppointment')),pg_temp.qid('doctorA'),'Professional member identity resolved to canonical doctor user');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('doctorB')::text,true);
select extensions.throws_ok($t$select pg_temp.qa_execute(jsonb_build_object('appointment_id',(select id from qa_actions where name='newAppointment'),'expected_status','scheduled'),'cancel_appointment')$t$,'42501',null,'Doctor cannot mutate another doctor appointment');
select extensions.throws_ok($t$select pg_temp.qa_execute(pg_temp.qa_create_args('{"local_time":"12:00"}'))$t$,'42501',null,'Doctor cannot create for another professional');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('foreign')::text,true);
select extensions.throws_ok($t$select * from public.execute_claimed_assistant_pending_action_for_current_user((select id from qa_actions where name='cancelDenied'))$t$,'42501',null,'Cross tenant actor cannot execute claimed action');
reset role;
update public.clinic_subscriptions set plan_id='basic' where clinic_id=pg_temp.qid('north');
set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.lives_ok($t$select * from public.create_appointment_for_current_user(pg_temp.qid('north'),pg_temp.qid('patient1'),pg_temp.qid('doctorA'),'Normal Agenda','','','','2030-01-08 18:00+00','2030-01-08 18:30+00')$t$,'Normal Basic scheduling remains available independently');
reset role;
update public.clinic_subscriptions set plan_id='pro' where clinic_id=pg_temp.qid('north');
set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('doctorA')::text,true);
select extensions.lives_ok($t$select pg_temp.qa_execute(pg_temp.qa_create_args('{"local_date":"2030-01-10","local_time":"12:30"}'))$t$,'Pro writable doctor creates own appointment through Assistant');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('assistant')::text,true);
select extensions.lives_ok($t$select pg_temp.qa_execute(pg_temp.qa_create_args('{"local_date":"2030-01-10","local_time":"13:30"}'))$t$,'Authorized assistant creates through canonical scheduling');
reset role; set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('admin')::text,true);
select extensions.lives_ok($t$select pg_temp.qa_execute(pg_temp.qa_create_args('{"local_date":"2030-01-10","local_time":"14:30"}'))$t$,'Authorized admin creates through canonical scheduling');
insert into qa_actions select 'expiry',id from public.create_assistant_pending_action_for_current_user(pg_temp.qid('north'),'cancel_appointment','{}',now()+interval '5 minutes');
select * from public.claim_assistant_pending_action_for_current_user((select id from qa_actions where name='expiry'));
reset role;
update public.assistant_pending_actions set created_at=now()-interval '2 minutes',expires_at=now()-interval '1 minute' where id=(select id from qa_actions where name='expiry');
set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('admin')::text,true);
select extensions.throws_ok($t$select * from public.execute_claimed_assistant_pending_action_for_current_user((select id from qa_actions where name='expiry'))$t$,'42501',null,'Expired claimed proposal cannot execute');
reset role;
delete from public.clinic_subscriptions where clinic_id=pg_temp.qid('north');
set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.throws_ok($t$select * from public.create_assistant_pending_action_for_current_user(pg_temp.qid('north'),'cancel_appointment','{}',now()+interval '5 minutes')$t$,'42501',null,'Missing subscription proposal denied');
select extensions.throws_ok($t$select * from public.execute_claimed_assistant_pending_action_for_current_user((select id from qa_actions where name='cancelDenied'))$t$,'42501',null,'Missing subscription execution denied');
select extensions.throws_ok($t$select * from public.list_appointment_assistant_activity_for_current_user(pg_temp.qid('north'))$t$,'42501',null,'Missing subscription history denied');
reset role;
insert into public.clinic_subscriptions(clinic_id,plan_id,status,billing_provider) values(pg_temp.qid('north'),'plus','past_due','manual');
set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('owner')::text,true);
select extensions.throws_ok($t$select public.save_appointment_assistant_settings_for_current_user(pg_temp.qid('north'),true,true,24,null,null,true)$t$,'42501',null,'Read-only settings denied');
reset role;
insert into public.appointment_automation_jobs(id,clinic_id,appointment_id,type,source_version,generation,scheduled_for,next_attempt_at,dedupe_key)
 select pg_temp.qid('dash-'||id::text),clinic_id,id,'reminder_email',starts_at,1,now()+interval '1 day',now()+interval '1 day','0059-dash-'||id::text from public.appointments where clinic_id=pg_temp.qid('north');
set local role authenticated; select set_config('request.jwt.claim.sub',pg_temp.qid('doctorA')::text,true);
select extensions.is((select count(*)::integer from public.get_appointment_automation_dashboard_for_current_user(pg_temp.qid('north')) where appointment_id=pg_temp.qid('appointmentB')),0,'Doctor dashboard excludes other professional appointment');
select extensions.ok((select count(*)>0 from public.get_appointment_automation_dashboard_for_current_user(pg_temp.qid('north'))),'Read-only doctor retains own historical dashboard');
reset role;
reset role;
update public.clinic_subscriptions set plan_id='plus',status='active',current_period_end=now()-interval '1 day' where clinic_id=pg_temp.qid('north');
select extensions.is((select public.clinic_has_effective_automation_subscription_internal(pg_temp.qid('north'))),true,'Automation active/now()-interval 1 day canonical authority');
update public.clinic_subscriptions set plan_id='plus',status='trialing',current_period_end=null where clinic_id=pg_temp.qid('north');
select extensions.is((select public.clinic_has_effective_automation_subscription_internal(pg_temp.qid('north'))),false,'Automation trialing/null canonical authority');
update public.clinic_subscriptions set plan_id='plus',status='trialing',current_period_end=now()-interval '1 day' where clinic_id=pg_temp.qid('north');
select extensions.is((select public.clinic_has_effective_automation_subscription_internal(pg_temp.qid('north'))),false,'Automation trialing/now()-interval 1 day canonical authority');
update public.clinic_subscriptions set plan_id='plus',status='trialing',current_period_end=now()+interval '1 day' where clinic_id=pg_temp.qid('north');
select extensions.is((select public.clinic_has_effective_automation_subscription_internal(pg_temp.qid('north'))),true,'Automation trialing/now()+interval 1 day canonical authority');
update public.clinic_subscriptions set plan_id='plus',status='past_due',current_period_end=null where clinic_id=pg_temp.qid('north');
select extensions.is((select public.clinic_has_effective_automation_subscription_internal(pg_temp.qid('north'))),false,'Automation past_due/null canonical authority');
update public.clinic_subscriptions set plan_id='plus',status='inactive',current_period_end=null where clinic_id=pg_temp.qid('north');
select extensions.is((select public.clinic_has_effective_automation_subscription_internal(pg_temp.qid('north'))),false,'Automation inactive/null canonical authority');
update public.clinic_subscriptions set plan_id='plus',status='cancelled',current_period_end=null where clinic_id=pg_temp.qid('north');
select extensions.is((select public.clinic_has_effective_automation_subscription_internal(pg_temp.qid('north'))),false,'Automation cancelled/null canonical authority');
update public.clinic_subscriptions set plan_id='plus',status='active',current_period_end=null where clinic_id=pg_temp.qid('north');
insert into public.appointment_automation_jobs(id,clinic_id,appointment_id,type,source_version,generation,scheduled_for,next_attempt_at,dedupe_key) values(pg_temp.qid('job'),pg_temp.qid('north'),pg_temp.qid('appointmentB'),'reminder_email','2030-01-07 15:00+00',1,now()-interval '1 minute',now()-interval '1 minute','0059-job');
create temp table qa_claim as select * from public.claim_due_appointment_automation_jobs('qa0059worker',1,90);
grant select on qa_claim to service_role;
update public.clinic_subscriptions set plan_id='basic' where clinic_id=pg_temp.qid('north'); set local role service_role;
select extensions.is((select public.begin_appointment_automation_delivery((select id from qa_claim),'qa0059worker',(select lease_token from qa_claim))),false,'Downgrade before dispatch denies new provider delivery');
select extensions.is((select public.finish_appointment_automation_job((select id from qa_claim),'qa0059worker',(select lease_token from qa_claim),'skipped','invalidated_entitlement',null)),true,'Denied pending work may be finalized safely');
reset role; update public.appointment_automation_jobs set status='processing',delivery_state='accepted',delivery_accepted_at=now(),locked_by='qa0059worker',locked_at=now(),lease_expires_at=now()-interval '1 second',lease_token=gen_random_uuid() where id=pg_temp.qid('job'); set local role service_role;
select extensions.lives_ok($t$select * from public.claim_due_appointment_automation_jobs('qa0059worker',1,90)$t$,'Accepted expired lease reconciles after downgrade');
reset role;
select extensions.is((select delivery_state from public.appointment_automation_jobs where id=pg_temp.qid('job')),'persisted'::text,'Accepted work persists without resend');
select extensions.ok((select bool_and(prosecdef and proconfig @> array['search_path=public, pg_temp']) from pg_proc where pronamespace='public'::regnamespace and proname='create_assistant_pending_action_for_current_user'),'create_assistant_pending_action_for_current_user: fixed definer search_path');
select extensions.ok((select bool_and(not has_function_privilege('anon',oid,'EXECUTE')) from pg_proc where pronamespace='public'::regnamespace and proname='create_assistant_pending_action_for_current_user'),'create_assistant_pending_action_for_current_user: anon denied');
select extensions.ok((select bool_and(prosecdef and proconfig @> array['search_path=public, pg_temp']) from pg_proc where pronamespace='public'::regnamespace and proname='claim_assistant_pending_action_for_current_user'),'claim_assistant_pending_action_for_current_user: fixed definer search_path');
select extensions.ok((select bool_and(not has_function_privilege('anon',oid,'EXECUTE')) from pg_proc where pronamespace='public'::regnamespace and proname='claim_assistant_pending_action_for_current_user'),'claim_assistant_pending_action_for_current_user: anon denied');
select extensions.ok((select bool_and(prosecdef and proconfig @> array['search_path=public, pg_temp']) from pg_proc where pronamespace='public'::regnamespace and proname='execute_claimed_assistant_pending_action_for_current_user'),'execute_claimed_assistant_pending_action_for_current_user: fixed definer search_path');
select extensions.ok((select bool_and(not has_function_privilege('anon',oid,'EXECUTE')) from pg_proc where pronamespace='public'::regnamespace and proname='execute_claimed_assistant_pending_action_for_current_user'),'execute_claimed_assistant_pending_action_for_current_user: anon denied');
select extensions.ok((select bool_and(prosecdef and proconfig @> array['search_path=public, pg_temp']) from pg_proc where pronamespace='public'::regnamespace and proname='finish_assistant_pending_action_for_current_user'),'finish_assistant_pending_action_for_current_user: fixed definer search_path');
select extensions.ok((select bool_and(not has_function_privilege('anon',oid,'EXECUTE')) from pg_proc where pronamespace='public'::regnamespace and proname='finish_assistant_pending_action_for_current_user'),'finish_assistant_pending_action_for_current_user: anon denied');
select extensions.ok((select bool_and(prosecdef and proconfig @> array['search_path=public, pg_temp']) from pg_proc where pronamespace='public'::regnamespace and proname='list_appointment_assistant_activity_for_current_user'),'list_appointment_assistant_activity_for_current_user: fixed definer search_path');
select extensions.ok((select bool_and(not has_function_privilege('anon',oid,'EXECUTE')) from pg_proc where pronamespace='public'::regnamespace and proname='list_appointment_assistant_activity_for_current_user'),'list_appointment_assistant_activity_for_current_user: anon denied');
select extensions.ok((select bool_and(prosecdef and proconfig @> array['search_path=public, pg_temp']) from pg_proc where pronamespace='public'::regnamespace and proname='get_appointment_automation_dashboard_for_current_user'),'get_appointment_automation_dashboard_for_current_user: fixed definer search_path');
select extensions.ok((select bool_and(not has_function_privilege('anon',oid,'EXECUTE')) from pg_proc where pronamespace='public'::regnamespace and proname='get_appointment_automation_dashboard_for_current_user'),'get_appointment_automation_dashboard_for_current_user: anon denied');
select extensions.ok((select bool_and(prosecdef and proconfig @> array['search_path=public, pg_temp']) from pg_proc where pronamespace='public'::regnamespace and proname='get_appointment_automation_scheduler_status_for_current_user'),'get_appointment_automation_scheduler_status_for_current_user: fixed definer search_path');
select extensions.ok((select bool_and(not has_function_privilege('anon',oid,'EXECUTE')) from pg_proc where pronamespace='public'::regnamespace and proname='get_appointment_automation_scheduler_status_for_current_user'),'get_appointment_automation_scheduler_status_for_current_user: anon denied');
select extensions.ok((select bool_and(prosecdef and proconfig @> array['search_path=public, pg_temp']) from pg_proc where pronamespace='public'::regnamespace and proname='begin_appointment_automation_delivery'),'begin_appointment_automation_delivery: fixed definer search_path');
select extensions.ok((select bool_and(not has_function_privilege('anon',oid,'EXECUTE')) from pg_proc where pronamespace='public'::regnamespace and proname='begin_appointment_automation_delivery'),'begin_appointment_automation_delivery: anon denied');
select * from extensions.finish(); rollback;