"use client";

import { Copy, Link2, RotateCcw, XCircle } from "lucide-react";
import { useActionState, useState } from "react";
import { Button } from "@/components/ui/button";

export function ConsentSigningLinkControls({ action, revokeAction, cancelAction, hasActiveLink }: { action: (state: { error?: string; url?: string; expiresAt?: string }, formData: FormData) => Promise<{ error?: string; url?: string; expiresAt?: string }>; revokeAction: () => Promise<void>; cancelAction: (formData: FormData) => Promise<void>; hasActiveLink: boolean }) {
  const [state, formAction] = useActionState(action, {});
  const [copied, setCopied] = useState(false);
  return <section className="mt-6 rounded-md border border-slate-200 p-4"><h2 className="font-bold text-ink">Enlace de firma</h2><p className="mt-2 text-sm text-slate-600">Este enlace permite revisar y firmar el consentimiento. Compartelo unicamente con el paciente correspondiente.</p><div className="mt-4 flex flex-wrap gap-3"><form action={formAction}><Button type="submit"><Link2 className="h-4 w-4" />{hasActiveLink ? "Regenerar enlace" : "Generar enlace de firma"}</Button></form>{hasActiveLink ? <form action={revokeAction}><Button type="submit" variant="secondary"><RotateCcw className="h-4 w-4" />Revocar enlace</Button></form> : null}</div>{state.url ? <div className="mt-4 rounded-md bg-teal-50 p-3"><p className="break-all text-sm text-slate-700">{state.url}</p><Button type="button" variant="ghost" className="mt-2" onClick={() => { void navigator.clipboard.writeText(state.url!); setCopied(true); }}><Copy className="h-4 w-4" />{copied ? "Copiado" : "Copiar enlace"}</Button></div> : null}{state.error ? <p role="alert" className="mt-3 text-sm text-rose-700">{state.error}</p> : null}<form action={cancelAction} className="mt-6 border-t border-slate-200 pt-5"><label htmlFor="cancellation_reason" className="text-sm font-semibold text-ink">Cancelar consentimiento</label><p className="mt-1 text-xs leading-5 text-slate-500">Solo es posible antes de la firma. El consentimiento se conservará como evidencia.</p><input id="cancellation_reason" name="cancellation_reason" maxLength={500} placeholder="Motivo opcional" className="mt-3 h-11 w-full rounded-md border border-slate-300 px-3 text-sm" /><Button type="submit" variant="secondary" className="mt-3 border-rose-300 text-rose-700 hover:bg-rose-50"><XCircle className="h-4 w-4" />Cancelar consentimiento</Button></form></section>;
}
