import Link from "next/link";
import { ArrowLeft, FileSignature, Plus } from "lucide-react";
import { notFound, redirect } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { ButtonLink } from "@/components/ui/button";
import { canCreateConsent } from "@/lib/clinical-record/permissions";
import { getConsentStatusLabel } from "@/lib/patients/detail";
import { getClinicalRecordForActiveTenant } from "@/lib/server/clinical-record";

export const dynamic = "force-dynamic";
export default async function PatientConsentsPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const result = await getClinicalRecordForActiveTenant(id, {}); if (result.state === "invalid_id" || result.state === "not_found") notFound(); if (result.state === "unauthenticated") redirect("/login"); if (result.state !== "ready") return <section className="rounded-lg border border-slate-200 bg-white p-5 text-sm text-slate-600">No tienes acceso a consentimientos clínicos.</section>; const { data } = result; return <><Link href={`/dashboard/patients/${id}/clinical-record`} className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-clinic"><ArrowLeft className="h-4 w-4" />Volver al expediente</Link><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold text-ink">Consentimientos</h1><p className="mt-1 text-sm text-slate-500">Registros de consentimiento de {data.patient.full_name}.</p></div>{canCreateConsent(data.tenant.membership.role) ? <ButtonLink href={`/dashboard/patients/${id}/consents/new`}><Plus className="h-4 w-4" />Nuevo consentimiento</ButtonLink> : null}</div><div className="grid gap-3">{data.consents.length ? data.consents.map((consent) => <Link key={consent.id} href={`/dashboard/patients/${id}/consents/${consent.id}`} className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm hover:bg-slate-50"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div><p className="font-semibold text-ink">{consent.consent_type}</p><p className="mt-1 text-sm text-slate-500">Firmas registradas: {consent.signatureCount}</p></div><Badge variant={consent.status === "signed" ? "green" : consent.status === "pending" ? "amber" : "slate"}>{getConsentStatusLabel(consent.status)}</Badge></div></Link>) : <p className="rounded-md bg-slate-50 p-4 text-sm text-slate-500">No hay consentimientos registrados.</p>}</div></>; }
