import Link from "next/link";
import { Plus, Search } from "lucide-react";
import { redirect } from "next/navigation";
import { PageHeader } from "@/components/dashboard/page-header";
import { Badge } from "@/components/ui/badge";
import { ButtonLink } from "@/components/ui/button";
import { clinicalTemplateSpecialties, normalizeTemplateFilters } from "@/lib/clinical-record/template-catalog";
import { listClinicalTemplates } from "@/lib/server/clinical-templates";

export const dynamic = "force-dynamic";
export default async function ClinicalTemplatesPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const filters = normalizeTemplateFilters(await searchParams);
  const result = await listClinicalTemplates({ kind: filters.kind, origin: filters.origin, specialty: filters.specialty, search: filters.search, active: filters.origin === "clinic" ? filters.status === "active" ? true : filters.status === "inactive" ? false : undefined : undefined });
  if (result.state === "unauthenticated") redirect("/login");
  if (result.state !== "ready") return <section className="rounded-lg border border-slate-200 bg-white p-5 text-sm text-slate-600">No fue posible cargar las plantillas.</section>;
  const system = result.data.templates.filter((template) => template.is_system_template);
  const clinic = result.data.templates.filter((template) => !template.is_system_template);
  const filterParams = new URLSearchParams(); if (filters.kind) filterParams.set("kind", filters.kind); if (filters.origin) filterParams.set("origin", filters.origin); if (filters.specialty) filterParams.set("specialty", filters.specialty); if (filters.status) filterParams.set("status", filters.status); if (filters.search) filterParams.set("q", filters.search);
  const queryString = filterParams.toString();
  const cards = (templates: typeof result.data.templates) => templates.length ? templates.map((template) => <Link key={template.id} href={`/dashboard/settings/clinical-templates/${template.id}`} className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm hover:bg-slate-50"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div><p className="font-semibold text-ink">{template.name}</p><p className="mt-1 text-sm text-slate-500">{template.specialty ?? "General / Multidisciplinaria"}</p><p className="mt-1 text-sm text-slate-500">{template.description ?? "Sin descripcion"}</p></div><div className="flex flex-wrap gap-2"><Badge variant={template.is_system_template ? "teal" : "slate"}>{template.is_system_template ? "CliniControl" : "Mi clínica"}</Badge><Badge variant={template.template_kind === "consent" ? "teal" : "slate"}>{template.template_kind === "consent" ? "Consentimiento" : "Nota"}</Badge>{!template.is_system_template ? <Badge variant={template.is_active ? "green" : "amber"}>{template.is_active ? "Activa" : "Inactiva"}</Badge> : null}</div></div></Link>) : <p className="rounded-md bg-slate-50 p-4 text-sm text-slate-500">No hay plantillas para estos filtros.</p>;
  return <><PageHeader title="Plantillas clinicas" description="Catálogo de apoyo documental y plantillas personalizadas de la clínica." action={result.data.canManage ? { label: "Nueva plantilla", href: "/dashboard/settings/clinical-templates/new", icon: <Plus className="h-4 w-4" /> } : undefined} /><p className="mb-5 rounded-md bg-amber-50 p-3 text-sm text-amber-800">Las plantillas son formatos de apoyo documental. Deben adaptarse al contexto clínico, los protocolos de la institución y la normativa aplicable.</p><form className="mb-6 grid gap-3 rounded-lg border border-slate-200 bg-white p-4 md:grid-cols-5"><label className="md:col-span-2"><span className="sr-only">Buscar plantilla</span><div className="flex items-center gap-2 rounded-md border border-slate-300 px-3"><Search className="h-4 w-4 text-slate-400" /><input name="q" defaultValue={filters.search} className="h-10 min-w-0 flex-1 outline-none" placeholder="Buscar por nombre" /></div></label><select name="specialty" defaultValue={filters.specialty ?? ""} className="h-11 rounded-md border border-slate-300 px-3 text-sm"><option value="">Todas las especialidades</option>{clinicalTemplateSpecialties.map((specialty) => <option key={specialty} value={specialty}>{specialty}</option>)}</select><select name="kind" defaultValue={filters.kind ?? ""} className="h-11 rounded-md border border-slate-300 px-3 text-sm"><option value="">Notas y consentimientos</option><option value="note">Notas</option><option value="consent">Consentimientos</option></select><select name="origin" defaultValue={filters.origin ?? ""} className="h-11 rounded-md border border-slate-300 px-3 text-sm"><option value="">Sistema y clínica</option><option value="system">CliniControl</option><option value="clinic">Mi clínica</option></select>{filters.origin === "clinic" ? <select name="status" defaultValue={filters.status ?? ""} className="h-11 rounded-md border border-slate-300 px-3 text-sm"><option value="">Todos los estados</option><option value="active">Activas</option><option value="inactive">Inactivas</option></select> : null}<ButtonLink href={`/dashboard/settings/clinical-templates${queryString ? `?${queryString}` : ""}`} variant="secondary" className="hidden">Actualizar</ButtonLink><button type="submit" className="h-11 rounded-md bg-clinic px-4 text-sm font-semibold text-white">Filtrar</button></form><section><h2 className="text-lg font-bold text-ink">Plantillas recomendadas del sistema</h2><p className="mt-1 text-sm text-slate-500">Duplícalas para adaptarlas a tu clínica.</p><div className="mt-4 grid gap-3">{cards(system)}</div></section><section className="mt-8"><h2 className="text-lg font-bold text-ink">Plantillas de mi clínica</h2><div className="mt-4 grid gap-3">{cards(clinic)}</div></section></>;
}
