import Link from "next/link";
import { ArrowLeft, ClipboardList, FileSignature, FileText, PenLine, Plus } from "lucide-react";
import { notFound, redirect } from "next/navigation";
import { PageHeader } from "@/components/dashboard/page-header";
import { Badge } from "@/components/ui/badge";
import { ButtonLink } from "@/components/ui/button";
import { canCreateClinicalNote, canCreateConsent } from "@/lib/clinical-record/permissions";
import { formatPatientTimestamp, getConsentStatusLabel, getMedicalNoteStatusLabel } from "@/lib/patients/detail";
import { getClinicalRecordForActiveTenant } from "@/lib/server/clinical-record";

export const dynamic = "force-dynamic";
function statusVariant(status: string) { return status === "signed" || status === "finalized" ? "green" as const : status === "pending" || status === "draft" ? "amber" as const : "slate" as const; }
export default async function ClinicalRecordPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ page?: string | string[]; note_created?: string | string[]; note_updated?: string | string[]; consent_created?: string | string[]; consent_signed?: string | string[] }> }) {
  const { id } = await params; const [result, query] = await Promise.all([getClinicalRecordForActiveTenant(id, await searchParams), searchParams]);
  if (result.state === "invalid_id" || result.state === "not_found") notFound(); if (result.state === "unauthenticated") redirect("/login");
  if (result.state !== "ready") return <section className="rounded-lg border border-slate-200 bg-white p-5"><h1 className="text-xl font-bold text-ink">Expediente no disponible</h1><p className="mt-2 text-sm text-slate-600">No tienes una membresía clínica activa o no fue posible cargar el expediente.</p></section>;
  const { data } = result; const role = data.tenant.membership.role; const message = query.consent_signed === "1" ? "El consentimiento se firmó correctamente." : query.consent_created === "1" ? "El consentimiento se creó correctamente." : query.note_updated === "1" ? "La nota clínica se actualizó correctamente." : query.note_created === "1" ? "La nota clínica se creó correctamente." : null;
  return <><Link href={`/dashboard/patients/${data.patient.id}`} className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-clinic"><ArrowLeft className="h-4 w-4" />Volver al paciente</Link>{message ? <p role="status" className="mb-5 rounded-md border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p> : null}<PageHeader title="Expediente clínico" description={`Registros clínicos de ${data.patient.full_name}.`} action={canCreateClinicalNote(role) ? { label: "Nueva nota", href: `/dashboard/patients/${data.patient.id}/notes/new`, icon: <Plus className="h-4 w-4" /> } : undefined} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><section className="rounded-lg border border-slate-200 bg-white p-4"><ClipboardList className="h-5 w-5 text-clinic" /><p className="mt-3 text-sm text-slate-500">Notas</p><p className="text-2xl font-bold text-ink">{data.totalNotes}</p></section><section className="rounded-lg border border-slate-200 bg-white p-4"><FileSignature className="h-5 w-5 text-clinic" /><p className="mt-3 text-sm text-slate-500">Consentimientos</p><p className="text-2xl font-bold text-ink">{data.consents.length}</p></section><section className="rounded-lg border border-slate-200 bg-white p-4"><PenLine className="h-5 w-5 text-clinic" /><p className="mt-3 text-sm text-slate-500">Firmas registradas</p><p className="text-2xl font-bold text-ink">{data.signatureCount}</p></section><section className="rounded-lg border border-slate-200 bg-white p-4"><FileText className="h-5 w-5 text-clinic" /><p className="mt-3 text-sm text-slate-500">Plantillas activas</p><p className="text-2xl font-bold text-ink">{data.templates.length}</p></section></div>
    <section className="mt-6 rounded-lg border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-lg font-bold text-ink">Notas clínicas</h2>{canCreateClinicalNote(role) ? <ButtonLink href={`/dashboard/patients/${data.patient.id}/notes/new`} className="h-10 px-3"><Plus className="h-4 w-4" />Nueva nota</ButtonLink> : null}</div><div className="mt-5 grid gap-3">{data.notes.length ? data.notes.map((note) => <article key={note.id} className="rounded-md border border-slate-200 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div className="min-w-0"><Link href={`/dashboard/patients/${data.patient.id}/notes/${note.id}`} className="font-semibold text-ink hover:text-clinic hover:underline">{note.specialty ?? note.templateName ?? "Nota clínica"}</Link><p className="mt-1 line-clamp-2 text-sm text-slate-500">{note.clinical_impression ?? "Sin resumen disponible"}</p><p className="mt-2 text-xs text-slate-500">{formatPatientTimestamp(note.created_at, data.tenant.clinic.timezone)} · {note.doctorName ?? "Sin registro"}</p></div><Badge variant={statusVariant(note.status)}>{getMedicalNoteStatusLabel(note.status)}</Badge></div></article>) : <p className="rounded-md bg-slate-50 p-4 text-sm text-slate-500">Este paciente no tiene notas clínicas.</p>}</div>{data.pageCount > 1 ? <nav className="mt-5 flex justify-between text-sm font-semibold text-clinic"><Link aria-disabled={data.page === 1} href={`/dashboard/patients/${data.patient.id}/clinical-record?page=${Math.max(1, data.page - 1)}`}>Anterior</Link><span className="text-slate-500">Página {data.page} de {data.pageCount}</span><Link aria-disabled={data.page === data.pageCount} href={`/dashboard/patients/${data.patient.id}/clinical-record?page=${Math.min(data.pageCount, data.page + 1)}`}>Siguiente</Link></nav> : null}</section>
    <section className="mt-6 rounded-lg border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-lg font-bold text-ink">Consentimientos</h2><div className="flex gap-3"><Link href={`/dashboard/patients/${data.patient.id}/consents`} className="text-sm font-semibold text-clinic hover:underline">Ver todos</Link>{canCreateConsent(role) ? <ButtonLink href={`/dashboard/patients/${data.patient.id}/consents/new`} className="h-10 px-3"><Plus className="h-4 w-4" />Nuevo</ButtonLink> : null}</div></div><div className="mt-5 grid gap-3 md:grid-cols-2">{data.consents.length ? data.consents.map((consent) => <Link key={consent.id} href={`/dashboard/patients/${data.patient.id}/consents/${consent.id}`} className="rounded-md border border-slate-200 p-4 hover:bg-slate-50"><div className="flex justify-between gap-3"><span className="font-semibold text-ink">{consent.consent_type}</span><Badge variant={statusVariant(consent.status)}>{getConsentStatusLabel(consent.status)}</Badge></div><p className="mt-2 text-sm text-slate-500">Firmas registradas: {consent.signatureCount}</p></Link>) : <p className="rounded-md bg-slate-50 p-4 text-sm text-slate-500">No hay consentimientos registrados.</p>}</div></section></>;
}
