"use client";
import { useActionState, useState } from "react";
import { Button } from "@/components/ui/button";
import { Field, Input, Select, Textarea } from "@/components/ui/input";
import { validateExceptionInput, type AvailabilityException } from "@/lib/availability/exceptions";
import { deactivateExceptionAction, manageExceptionAction } from "@/app/dashboard/settings/availability/exception-actions";

export function ProfessionalAvailabilityExceptions({ professionalId, canEdit, timezone, exceptions }: { professionalId: string; canEdit: boolean; timezone: string; exceptions: AvailabilityException[] }) {
  const [editing, setEditing] = useState<AvailabilityException | null>(null); const [state, action] = useActionState(manageExceptionAction, { state: "idle" });
  const [allDay, setAllDay] = useState(false); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [startTime, setStartTime] = useState(""); const [endTime, setEndTime] = useState(""); const [type, setType] = useState("unavailable"); const [reason, setReason] = useState("");
  const beginEdit = (item: AvailabilityException) => { setEditing(item); setType(item.exception_type); const start = new Date(item.start_at); const end = new Date(item.end_at); const date = (v: Date) => new Intl.DateTimeFormat("en-CA", { timeZone: timezone, year: "numeric", month: "2-digit", day: "2-digit" }).format(v); const time = (v: Date) => new Intl.DateTimeFormat("en-GB", { timeZone: timezone, hour: "2-digit", minute: "2-digit", hour12: false }).format(v); setStartDate(date(start)); setEndDate(date(end)); setStartTime(time(start)); setEndTime(time(end)); setReason(item.reason ?? ""); setAllDay(false); };
  const reset = () => { setEditing(null); setStartDate(""); setEndDate(""); setStartTime(""); setEndTime(""); setReason(""); setAllDay(false); setType("unavailable"); };
  const validation = validateExceptionInput({ type, startDate, startTime, endDate, endTime, allDay, reason });
  return <section className="mt-6 glass-card-strong p-4 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold text-ink">Excepciones y bloqueos</h2><p className="mt-1 text-sm text-slate-600">Vacaciones, bloqueos o aperturas especiales sin modificar tu horario habitual.</p></div><p className="glass-control px-3 py-2 text-sm text-slate-700">Zona horaria: <strong>{timezone}</strong></p></div>
    {canEdit ? <form action={action} className="clinical-surface mt-5 grid gap-3 p-4"><input type="hidden" name="action" value={editing ? "update" : "create"}/><input type="hidden" name="exception_id" value={editing?.id ?? ""}/><input type="hidden" name="professional_id" value={professionalId}/><div className="grid gap-3 sm:grid-cols-2"><Field label="Tipo" htmlFor="exception_type"><Select id="exception_type" name="exception_type" value={type} onChange={(e) => setType(e.target.value)}><option value="unavailable">No disponible</option><option value="available">Disponibilidad extraordinaria</option></Select></Field><Field label="Motivo (opcional)" htmlFor="reason"><Textarea id="reason" name="reason" value={reason} onChange={(e) => setReason(e.target.value)} maxLength={300} rows={1}/></Field><Field label="Fecha inicio" htmlFor="start_date"><Input id="start_date" name="start_date" type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} required/></Field><Field label="Fecha fin" htmlFor="end_date"><Input id="end_date" name="end_date" type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} required/></Field></div><label className="flex items-center gap-2 text-sm font-semibold text-ink"><input name="all_day" type="checkbox" checked={allDay} onChange={(e) => setAllDay(e.target.checked)} className="h-4 w-4"/>Todo el día</label>{!allDay ? <div className="grid gap-3 sm:grid-cols-2"><Field label="Hora inicio" htmlFor="start_time"><Input id="start_time" name="start_time" type="time" value={startTime} onChange={(e) => setStartTime(e.target.value)} required/></Field><Field label="Hora fin" htmlFor="end_time"><Input id="end_time" name="end_time" type="time" value={endTime} onChange={(e) => setEndTime(e.target.value)} required/></Field></div> : null}<div className="flex flex-wrap justify-end gap-2"><Button type="submit" disabled={Boolean(validation)}>{editing ? "Actualizar" : "Guardar"}</Button>{editing ? <Button type="button" variant="ghost" onClick={reset}>Cancelar</Button> : null}</div>{validation ? <p className="text-sm text-amber-800" role="status">{validation}</p> : null}{state.state === "error" ? <p className="text-sm font-semibold text-rose-800" role="alert">{state.error}</p> : null}{state.state === "success" ? <p className="text-sm font-semibold text-emerald-800" role="status">Excepción guardada.</p> : null}</form> : <p className="clinical-surface mt-5 p-4 text-sm text-slate-600">Tu rol puede consultar excepciones, pero no modificarlas.</p>}
    <div className="mt-5 grid gap-3">{exceptions.length ? exceptions.map((item) => <article key={item.id} className="clinical-surface flex flex-wrap items-start justify-between gap-3 p-4"><div><p className="font-semibold text-ink">{item.exception_type === "available" ? "Disponibilidad extraordinaria" : "No disponible"}</p><p className="text-sm text-slate-600">{new Intl.DateTimeFormat("es-MX", { timeZone: timezone, dateStyle: "medium", timeStyle: "short" }).format(new Date(item.start_at))} – {new Intl.DateTimeFormat("es-MX", { timeZone: timezone, dateStyle: "medium", timeStyle: "short" }).format(new Date(item.end_at))}</p>{item.reason ? <p className="mt-1 text-sm text-slate-500">{item.reason}</p> : null}</div>{canEdit ? <div className="flex gap-2"><Button type="button" variant="secondary" onClick={() => beginEdit(item)}>Editar</Button><form action={deactivateExceptionAction}><input type="hidden" name="action" value="deactivate"/><input type="hidden" name="exception_id" value={item.id}/><input type="hidden" name="professional_id" value={professionalId}/><Button type="submit" variant="ghost">Eliminar</Button></form></div> : null}</article>) : <p className="clinical-surface p-4 text-sm text-slate-500">No hay excepciones activas.</p>}</div>
  </section>;
}
