import "server-only";
import { requirePlatformAdmin } from "@/lib/admin/require-platform-admin";
import { createAdminClient } from "@/lib/supabase/admin";
import { logger } from "@/lib/logger";
import { isSupportUuid, isSafeSupportCode } from "@/lib/support/security";
import { parseSupportMessage } from "@/lib/support/tickets";

const statuses = ["open","triaged","in_progress","waiting_user","resolved","closed"] as const;
const transitions: Record<string,string[]> = { open:["triaged"], triaged:["in_progress"], in_progress:["waiting_user","resolved"], waiting_user:["in_progress"] , resolved:["closed"], closed:[] };
export type AdminSupportQuery = { status?: string; severity?: string; category?: string; assigned?: "assigned"|"unassigned"; clinic?: string; page?: number };
const safeTicket = "id, reference_code, clinic_id, created_by, category, severity, status, subject, summary, diagnostic_codes, assigned_to, last_activity_at, created_at, updated_at, resolved_at, closed_at";

async function guard() { return requirePlatformAdmin(); }
async function audit(admin: any, actor: string, ticketId: string, action: string, metadata: Record<string,string> = {}) {
  const ticket = await admin.from("support_tickets").select("clinic_id").eq("id", ticketId).maybeSingle();
  if (ticket.error || !ticket.data?.clinic_id) return;
  await admin.from("audit_logs").insert({ clinic_id: ticket.data.clinic_id, actor_user_id: actor, entity_type: "support_ticket", entity_id: ticketId, action, metadata }).then((r:any) => { if (r.error) logger.error("Support audit write failed", { component:"support_admin", operation:"audit", status:"failed", code:r.error.code }); });
}
export async function listAdminSupportTickets(query: AdminSupportQuery = {}) {
  const user = await guard(); const admin: any = createAdminClient(); let q:any = admin.from("support_tickets").select(safeTicket,{count:"exact"});
  if (statuses.includes(query.status as any)) q=q.eq("status",query.status);
  if (["low","normal","high"].includes(query.severity ?? "")) q=q.eq("severity",query.severity);
  if (isSafeSupportCode(query.category ?? "")) q=q.eq("category",query.category);
  if (query.assigned === "assigned") q=q.not("assigned_to","is",null); if (query.assigned === "unassigned") q=q.is("assigned_to",null);
  if (isSupportUuid(query.clinic ?? "")) q=q.eq("clinic_id",query.clinic);
  const page=Math.max(1,Math.min(100,query.page ?? 1)); const from=(page-1)*25; const result=await q.order("last_activity_at",{ascending:false}).range(from,from+24);
  if(result.error){ logger.error("Support admin query failed",{component:"support_admin",operation:"list",status:"failed",code:result.error.code}); return {state:"error" as const,data:null}; }
  const rows=result.data??[]; const clinics=await admin.from("clinics").select("id,name").in("id",rows.map((r:any)=>r.clinic_id)); const names=new Map((clinics.data??[]).map((c:any)=>[c.id,c.name]));
  return {state:"ready" as const,data:{rows:rows.map((r:any)=>({...r,clinic_name:names.get(r.clinic_id)??"Clínica no disponible"})),page,total:result.count??0,pageCount:Math.max(1,Math.ceil((result.count??0)/25))},actor:user};
}
export async function getAdminSupportTicket(id:string){ const user=await guard(); if(!isSupportUuid(id)) return {state:"not_found" as const,data:null}; const admin=createAdminClient(); const t=await admin.from("support_tickets").select(safeTicket).eq("id",id).maybeSingle(); if(t.error||!t.data) return {state:"not_found" as const,data:null}; const [m,e,c,a]=await Promise.all([admin.from("support_ticket_messages").select("id,author_user_id,author_kind,visibility,body,created_at,redacted_at").eq("ticket_id",id).order("created_at"),admin.from("support_ticket_events").select("id,event_type,from_status,to_status,safe_metadata,created_at").eq("ticket_id",id).order("created_at"),admin.from("clinics").select("id,name").eq("id",(t.data as any).clinic_id).maybeSingle(),admin.from("platform_admins").select("user_id").order("user_id")]); if(m.error||e.error||c.error) return {state:"error" as const,data:null}; return {state:"ready" as const,data:{ticket:{...(t.data as any),clinic_name:(c.data as any)?.name??"Clínica no disponible"},messages:m.data??[],events:e.data??[],admins:a.data??[]},actor:user}; }
export async function transitionAdminSupportTicket(id:string,toStatus:string){ const user=await guard(); if(!isSupportUuid(id)||!statuses.includes(toStatus as any)) return {state:"invalid_input" as const}; const admin=createAdminClient(); const t=await admin.from("support_tickets").select("id,status,category,severity,clinic_id").eq("id",id).maybeSingle(); const from=(t.data as any)?.status; if(!from||!transitions[from]?.includes(toStatus)) return {state:"invalid_transition" as const}; const patch:any={status:toStatus,last_activity_at:new Date().toISOString(),updated_at:new Date().toISOString()}; if(toStatus==="resolved") patch.resolved_at=new Date().toISOString(); if(toStatus==="closed") patch.closed_at=new Date().toISOString(); const u=await admin.from("support_tickets").update(patch).eq("id",id); if(u.error) return {state:"error" as const}; await admin.from("support_ticket_events").insert({ticket_id:id,actor_user_id:user.id,event_type:"support_ticket_status_changed",from_status:from,to_status:toStatus}); await audit(admin,user.id,id,toStatus==="triaged"?"support_ticket_triaged":"support_ticket_status_changed",{ticket_id:id,from_status:from,to_status:toStatus}); return {state:"ready" as const}; }
export async function assignAdminSupportTicket(id:string,assignedTo:string|null){ const user=await guard(); if(assignedTo!==null&&!isSupportUuid(assignedTo)) return {state:"invalid_input" as const}; const admin=createAdminClient(); if(assignedTo){const p=await admin.from("platform_admins").select("user_id").eq("user_id",assignedTo).maybeSingle(); if(!p.data)return {state:"invalid_input" as const};} const u=await admin.from("support_tickets").update({assigned_to:assignedTo,last_activity_at:new Date().toISOString()}).eq("id",id); if(u.error)return {state:"error" as const}; await admin.from("support_ticket_events").insert({ticket_id:id,actor_user_id:user.id,event_type:"support_ticket_assignment_changed",safe_metadata:{assignment_state:assignedTo?"assigned":"unassigned"}}); await audit(admin,user.id,id,"support_ticket_assignment_changed",{ticket_id:id}); return {state:"ready" as const}; }
export async function addAdminSupportMessage(id:string,body:string,internal:boolean){ const user=await guard(); const parsed=parseSupportMessage(body); if(!isSupportUuid(id)||!parsed)return {state:"invalid_input" as const}; const admin=createAdminClient(); const r=await admin.from("support_ticket_messages").insert({ticket_id:id,author_user_id:user.id,author_kind:"platform_admin",visibility:internal?"internal":"requester",body:parsed}).select("id,author_user_id,author_kind,visibility,body,created_at").single(); if(r.error)return {state:"error" as const}; await admin.from("support_tickets").update({last_activity_at:new Date().toISOString()}).eq("id",id); await admin.from("support_ticket_events").insert({ticket_id:id,actor_user_id:user.id,event_type:"support_ticket_message_added",safe_metadata:{visibility:internal?"internal":"requester"}}); await audit(admin,user.id,id,internal?"support_ticket_internal_note_added":"support_ticket_admin_reply_added",{ticket_id:id}); return {state:"ready" as const,data:r.data}; }
